### ISSUE TITLE
Consider using JSON schema

### ISSUE THREAD

**Issue by vks** [theupdateframework/python-tuf#358] opened 2016-08-08 20:28 UTC
Instead of the DSL implemented in schema.py, it would be nice to use [JSON schema](http://json-schema.org). This would make it easier to implement tuf in other languages, because the schemas could be easily reused.

**Comment by ivanayov** [comment] 2022-02-16 09:41
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

**More details**

Current source code (and upcoming 1.0 release) only contains the modern components

* a low-level Metadata API (`tuf.api`) and
* `tuf.ngclient` that implements the client workflow,
*
Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed** 2022-02-16 09:46 UTC
Labels: enhancement

**Comment by jku** [comment] 2022-02-16 09:49
note that we're still not using json schemas so the feature request could still be valid ... it is just quite unlikely we'd go that way now.
