### ISSUE TITLE
Role can use key without calling load_signing_key first

### ISSUE THREAD

**Issue by awwad** [theupdateframework/python-tuf#646] opened 2018-03-16 20:14 UTC
I'm going to keep this one brief while I investigate it, rather than providing tons of context.

Unexpected (by me) behavior in repository_tool:

If some role A delegates to some role B, listing (public) key K as an expected key for role B, and any role currently has key K loaded, then regardless of whether or not role B has key K loaded, role B will be signed with key K when it (role B) is written.

I don't expect this behavior because when signing role B, role B's state should be the sole determinant of what keys it is signed by.

Same thing, put another way:
Scenario:
Given:
- Role A delegates \* to role B, listing public key for Key K
- Any *other* role already has Key K loaded (via .load_signing_key()).

Result:
Role B is signed by role K when it is written, even though there was no B.load_signing_key(K) call.

**Comment by awwad** [comment] 2018-03-16 20:24
Note to self: what if you unload a signing key from one role. Would it be unloaded for all roles?

Investigation starts in write().

**Comment by ivanayov** [comment] 2022-02-16 14:34
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

**More details**

Current source code (and upcoming 1.0 release) only contains the modern components

* a low-level Metadata API (`tuf.api`) and
* `tuf.ngclient` that implements the client workflow,

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed by ivanayov** 2022-02-16 14:34 UTC
Labels: bug
