### ISSUE TITLE
Create roles independently from tuf.repository_tool.Targets.delegate()

### ISSUE THREAD

**Issue by awwad** [theupdateframework/python-tuf#820] opened 2019-01-08 17:54 UTC
Related to #660 .

Long ago in the reference implementation, creating a delegation was equivalent to creating a role.  That is not the case, however, as a delegation can point to an existing role.  Accordingly, the Targets class method 'delegate()' creates a role.  We made some changes previously to allow delegate() to work even if the role to delegate to already exists, but the code is still confusing in this regard.  It's probably best to separate role creation from delegation to that role.

**Comment by jku** [comment] 2022-02-16 12:58
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

### More details

Current source code (and upcoming 1.0 release) only contains the modern components
 * a low-level Metadata API (`tuf.api`) and 
 * `tuf.ngclient` that implements the client workflow, 

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed by jku** 2022-02-16 12:58 UTC
Labels: enhancement, good first issue, up for grabs
