### ISSUE TITLE
Promiscuous delegation not supported correctly

### ISSUE THREAD

**Issue by awwad** [theupdateframework/python-tuf#658] opened 2018-03-23 18:19 UTC
Note that the larger issue is now captured in #660.

If roles A and B delegate to role C, and roles A and B have nonidentical expectations of signatures over role C, then if role C is signed by the keys B expects but not the keys that A expects, then role C may fail to be validated whether it is reached from role A or role B, even if the delegation pathways are entirely distinct in terms of the target namespaces used.

[This script](https://github.com/theupdateframework/specification/issues/17#issuecomment-369651855) can be used to experiment with this phenomenon.

The quick diagnosis specific to this issue is:

`updater._verify_uncompressed_metadata_file()` calls `tuf.sig.verify`, which calls `roledb.get_role_keyids()`, and `get_role_keyids` takes only the name of a role (and a repository name), purporting to return the keys that that role should be signed by. In this case, get_role_keyids(C) cannot be expected to return the correct answer to the question "What keys should role A expect role C to be signed by?" The answers are different for roles A and B. We seek information about a delegation, not a delegated role, so get_role_keyids() doesn't make sense. See #660.

**Comment by ivanayov** [comment] 2022-02-16 14:31
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

**More details**

Current source code (and upcoming 1.0 release) only contains the modern components

* a low-level Metadata API (`tuf.api`) and
* `tuf.ngclient` that implements the client workflow,

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed by ivanayov** 2022-02-16 14:31 UTC
