### ISSUE TITLE
tuf.conf.repository_directory is not working as expected on Windows

### ISSUE THREAD

**Issue by fiskeren** [theupdateframework/python-tuf#454] opened 2017-06-02 13:39 UTC
Hi!

I am using the example from https://github.com/theupdateframework/tuf/tree/master/tuf/client to create a simple updater on a windows machine.
The tuf.conf.repository is set to '.' , but I keep getting the error: PermissionError: [WinError 5] Access is denied: 'C:\\' 
Which could indicate the the full path of the working dir is not sent to the os as expected.
To troubleshoot, I create some basic print(destination) on the updater.py (https://github.com/theupdateframework/tuf/blob/master/tuf/client/updater.py#L2902-L2905)

destination = os.path.join(destination_directory,
                               target_filepath.lstrip(os.sep))
print(destination)
destination = os.path.abspath(destination)
print(destination)
target_dirpath = os.path.dirname(destination)
print(target_dirpath)
 
This resulted in the following output:
/file1.txt
C:\file1.txt
C:\

This means that the full path (C:\Users\user\Desktop\testing) is not sent to the os.makedirs function.

**Comment by vladimir-v-diaz** [comment] 2017-06-02 18:22
Here is the behaviour on a Linux machine:

```Bash
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.join('.', '/file1.txt'.lstrip(os.sep))
'./file1.txt'
>>> os.path.abspath(_)
'/home/projects/tuf/tuf/client/file1.txt'
>>> os.path.dirname(_)
'/home/projects/tuf/tuf/client'
>>> 
```

On Windows, the '.' (for current directory) and the drive letter appear to have been discarded.  This behaviour seems to fall in line with the documentation on os.path.join() on Windows: https://docs.python.org/2/library/os.path.html#os.path.join

Can you test whether `os.path.normpath()` retains the '.' and drive letter on your Windows environment?
Try the following, or similar...

```Bash
>>> destination_directory = os.path.normpath(destination_directory)
>>> os.path.join(destination_directory, target_filepath.lstrip(os.sep))

**Comment by AStrunk** [comment] 2017-06-06 07:15
OK, I ended up with the following example, which seems to work. 
First I get the current working dir. This could be anything such as C:\Dir1\dir2\dir3\. Then I split it with "\\" as separator, which creates an array, b. 
I then take the file that is getting downloaded from the repo - this would normally be from a dict (target['filepath']) but for sake of the example, I'm just calling is target_filepath - I strip the "/" from the start of it and append it to the array b. 
I den join the array with "\\"

Example code looks like this:
`import os
destination_directory = os.path.dirname(os.path.realpath(__file__))
b = destination_directory.split(sep='\\')

print("\\".join(b))
target_filepath = "/file1.txt"
c = target_filepath.strip("/")
b.append(c)
print("\\".join(b))
`

This gives the output:
C:\workdir
C:\workdir\file1.txt

**Comment by AStrunk** [comment] 2017-06-06 07:43
The updated updater.py code could look like this:

```
    if os.name == 'nt':
        b = destination_directory.split(sep='\\')
        c = target_filepath.strip("/")
        b.append(c)
        destination = os.path.abspath("\\".join(b))
        target_dirpath = os.path.dirname(destination)
    if os.name != 'nt':
        destination = os.path.join(destination_directory,
                                   target_filepath.lstrip(os.sep))
        destination = os.path.abspath(destination)

```

**Comment by ivanayov** [comment] 2022-02-16 14:25
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

**More details**

Current source code (and upcoming 1.0 release) only contains the modern components

* a low-level Metadata API (`tuf.api`) and
* `tuf.ngclient` that implements the client workflow,

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed by ivanayov** 2022-02-16 14:25 UTC
